#!/usr/bin/env bash
# Create C header with arrays containing references to all variable names
# Reads list of file names from stdin

count=0
arrnames=()
while read arrname
do
  arrnames=( "${arrnames[@]}" "${arrname}" )
  # Output variable name for header
  count=$((count + 1))
done

echo "/* AUTOGENERATED HEADER - DO NOT EDIT */"
echo

echo "#include <stddef.h>" # For size_t
echo

# Print out header file
for arrname in "${arrnames[@]}"
do
  echo "extern const char $arrname[];"
  echo "extern const size_t ${arrname}_len;"
done
echo

# Arrays indexing above variables
data_arr=file2array_data
len_arr=${data_arr}_lens
name_arr=${data_arr}_names
echo "static const char *${data_arr}[${count}];"
echo "static size_t ${len_arr}[${count}];"
echo "static const char *${name_arr}[${count}];"
echo "static const size_t file2array_data_len = $count;"
echo

# Generate initializer function for arrays
echo "static inline void file2array_data_init(void) {"

i=0
for arrname in "${arrnames[@]}"
do
  echo "  ${data_arr}[${i}] = $arrname;"
  echo "  ${len_arr}[${i}] = ${arrname}_len;"
  echo "  ${name_arr}[${i}] = \"${arrname}\";"
  i=$(($i + 1))
done
echo "}"
echo
