
= Swift/T Quick Start

Swift/T is an implicitly parallel programming language for composing external functions and command-line executables into massively parallel applications.  The external functions may be calls to external programs, libraries, or scripting languages (via embedded interpreters)  Thus, it is a _workflow language_ for extreme-scale computing, capable of executing very large numbers (trillions) of tasks at high rates across the largest supercomputers.

Swift/T runs as an MPI program, and is compatible with Cray and IBM supercomputers, as well as PBS, SLURM, LSF, or Cobalt clusters, and can also run on a laptop (Linux or Mac).

Swift/T may be installed following one of these methods:

* https://spack.io[Spack]
+
----
$ spack install stc
----
* https://conda.io[Conda]
+
----
$ conda install -c swift-t swift-t
----
* Debian (Ubuntu) packages
* A script (+build-swift-t.sh+) that automates the +configure+/+make+ process
* A +configure+/+make+ source build (recommended for exotic systems)

Installation notes are here: http://swift-lang.github.io/swift-t/guide.html#_installation

== Links

* http://swift-lang.org/Swift-T[The Swift/T front page]

* http://swift-lang.github.io/swift-t/downloads.html[Swift/T Downloads]

* http://swift-lang.github.io/swift-t/guide.html[The Swift/T Guide]: manual for the language and runtime

* http://swift-lang.github.io/swift-t/sites.html[The Sites Guide]: guidance for building and running Swift/T on various systems

* http://swift-lang.github.io/swift-t/dev.html[The Developers' Guide]: guidance for developers who wish to extend or modify Swift/T
