#!/bin/zsh
# Copyright 2013 University of Chicago and Argonne National Laboratory
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

# Generate linear-*.tcl, a tcl-turbine test case

COUNT=$1

if [[ ${COUNT} == "" ]]
then
  print "Not given: COUNT"
  return 1
fi

OUTPUT="linear-${COUNT}.tcl"

alias spacer='print >> ${OUTPUT}'

spacer

# Header
{
  print "# Generated by mk-linear.zsh"
  print "package require turbine 0.1"
  print "turbine_init"
} > ${OUTPUT}

spacer

# Data declarations
for (( i=0 ; i<COUNT ; i++ ))
do
  print "turbine_file ${i} ${i}.txt"
done >> ${OUTPUT}

spacer

# Task dependencies
print "turbine_rule 0 0 { } { 0 } { touch 0.txt }" >> ${OUTPUT}
for (( i=1 ; i<COUNT ; i++ ))
do
  PREV=$(( i-1 ))
  printf "turbine_rule ${i} ${i} { ${PREV} } { ${i} } "
  print "{ touch ${i}.txt }"
done >> ${OUTPUT}

spacer

# Footer
{
  print "turbine_engine"
  print "turbine_finalize"
  print "puts OK"
} >> ${OUTPUT}

print "wrote: ${OUTPUT}"

return 0
