
/*
  BLOB.H

  Binary Large OBjects

  The Tcl bindings for all this are generated by SWIG
*/

/**
   Simple struct for variable-length data blob
*/
typedef struct
{
  void* pointer;
  int length;
} SwiftBlob;

SwiftBlob* SwiftBlob_make_test(void);

int SwiftBlob_sizeof_float(void);

int SwiftBlob_pointer_as_integer(void* p);
double* SwiftBlob_cast_to_pointer(int i);
double SwiftBlob_double_get(SwiftBlob* data, int index);
char SwiftBlob_char_get(SwiftBlob* data, int index);
void* SwiftBlob_allocate(int bytes);
void SwiftBlob_store_double(void* p, int i, double d);
void SwiftBlob_free(SwiftBlob* blob);
