name: Build and Test 🧪

on:
  # Schedule and workflow_dispatch (manual) only work on default branch
  schedule:
    - cron: "0 6 * * *"   # Fire at 06:00 AM every day
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - github_action_mac
#      - github_action_build   # The name of our test branch
#      - master
  release:
    types:
      - published

permissions:
  contents: read    # To read the project source code (git)
#  packages: read    # To read the docker image from package registry

jobs:
  build_swift-t:
    name: Build swift-t on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
#          - ubuntu-latest
          - macos-14

        # Comman separated list of python versions to test
        python-version: ["3.11"]

        mpi:
          - mpich

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          brew update
          brew install tcl-tk java autoconf automake make mpich swig
          which make gmake
#        run: sudo apt-get install -y zsh tcl tcl-dev default-jdk autoconf make libcurl4-openssl-dev

#       - name: Set up R
#         uses: r-lib/actions/setup-r@v2

#       # TODO RInside
#       - name: Install R requirements
#         run: R -e "install.packages('RInside')"
# #        run: Rscript install/R-requirements.R

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::RInside


#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ matrix.python-version }}
# #          cache: pip

#       - name: Upgrade pip
#         run:  python -m pip install -U pip

      - name: Initialize swift-t settings
        run: dev/build/init-settings.sh

      # TODO set swift-t install, R, python, and ??
      # sed -i 's/original/new/g' file.txt
#      - run: sed -i 's/ENABLE_PYTHON=0/ENABLE_PYTHON=1/g' dev/build/swift-t-settings.sh

#      - run: sed -i 's/ENABLE_R=0/ENABLE_R=1/g' dev/build/swift-t-settings.sh

      - name: build swift-t
        run: |
          # For GNU Make:
          echo GITHUB_PATH $GITHUB_PATH
          cat $GITHUB_PATH
          echo /opt/homebrew/opt/make/libexec/gnubin >> $GITHUB_PATH
          cat $GITHUB_PATH
          ls /opt/homebrew/opt/make/libexec/gnubin
          dev/build/build-swift-t.sh -vv

      # TODO check swift-t install
      - name: Check swift-t version info
        run: /tmp/swift-t-install/stc/bin/swift-t -v
