name: Build and Test 🧪

on:
  # Schedule and workflow_dispatch (manual) only work on default branch
  schedule:
    - cron: "30 4 * * *"   # Fire at 04:30 AM every day
  workflow_dispatch:
  pull_request:
  push:
    branches:
      # - github_action_mac
      # - github_action_build   # The name of our test branch
      - master
  release:
    types:
      - published

permissions:
  contents: read    # To read the project source code (git)

jobs:
  build_swift-t:
    name: OS=${{ matrix.os }} PY=${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-14

        # Comma separated list of python versions to test
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

        mpi:
          - mpich

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          dev/github-actions/setup-deps.sh ${{ matrix.os }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup R
        run: |
          dev/github-actions/install-R.sh ${{ matrix.os }}

      - name: Initialize swift-t settings
        run: |
          dev/build/init-settings.sh
          dev/github-actions/edit-settings.sh -r

      - name: build swift-t
        run: |
          dev/build/build-swift-t.sh

      - name: Report Swift/T version info
        run:  /tmp/swift-t-install/stc/bin/swift-t -v

      - name: Check that Swift/T runs
        run:  |
          /tmp/swift-t-install/stc/bin/swift-t -E 'trace(42);'
          /tmp/swift-t-install/stc/bin/swift-t -i python -E 'trace(python("","repr(42)"));'
