name: Swift/T Test Suite 🧪

on:
  # Schedule and workflow_dispatch (manual) only work on default branch
  schedule:
    - cron: "30 4 * * 1"   # Fire at 04:30 AM every Monday
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published

permissions:
  contents: read    # To read the project source code (git)

jobs:
  stc_test_suite_valgrind:
    name: Suite O${{ matrix.opt-level }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

        # Optimization levels to test for STC
        opt-level:
          - "0"
          - "1"
          - "2"
          - "3"

        # Comma separated list of python versions to test
        python-version:
          - "3.10"

        mpi:
          - openmpi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          # auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Install deps
        run: |
          dev/github-actions/setup-deps.sh ${{ matrix.os }}

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Initialize swift-t settings
        run: |
          dev/build/init-settings.sh
          dev/github-actions/edit-settings.sh

      - name: build swift-t
        run: |
          dev/build/build-swift-t.sh

      - name: Report Swift/T version info
        run:  /tmp/swift-t-install/stc/bin/swift-t -v

      - name: Run STC Test Suite at O${{ matrix.opt-level }} under Valgrind
        run: |
          export STC=/tmp/swift-t-install/stc/bin/stc
          export TURBINE_HOME=/tmp/swift-t-install/turbine
          export VALGRIND=$(which valgrind)
          cd stc/tests
          set -x
          ./run-tests.zsh -O${{ matrix.opt-level }} -e
